# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.5.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QGroupBox, QLabel,
    QListWidget, QListWidgetItem, QMainWindow, QPushButton,
    QRadioButton, QSizePolicy, QSlider, QStatusBar,
    QTextEdit, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.MapSelect = QComboBox(self.centralwidget)
        self.MapSelect.setObjectName(u"MapSelect")
        self.MapSelect.setEnabled(False)
        self.MapSelect.setGeometry(QRect(650, 100, 131, 22))
        self.StartAtSelectedMap = QRadioButton(self.centralwidget)
        self.StartAtSelectedMap.setObjectName(u"StartAtSelectedMap")
        self.StartAtSelectedMap.setGeometry(QRect(650, 80, 91, 18))
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartAtSelectedMap.sizePolicy().hasHeightForWidth())
        self.StartAtSelectedMap.setSizePolicy(sizePolicy)
        self.FirstMapStart = QRadioButton(self.centralwidget)
        self.FirstMapStart.setObjectName(u"FirstMapStart")
        self.FirstMapStart.setGeometry(QRect(650, 60, 101, 18))
        sizePolicy.setHeightForWidth(self.FirstMapStart.sizePolicy().hasHeightForWidth())
        self.FirstMapStart.setSizePolicy(sizePolicy)
        self.MainMenuStart = QRadioButton(self.centralwidget)
        self.MainMenuStart.setObjectName(u"MainMenuStart")
        self.MainMenuStart.setGeometry(QRect(650, 40, 111, 18))
        sizePolicy.setHeightForWidth(self.MainMenuStart.sizePolicy().hasHeightForWidth())
        self.MainMenuStart.setSizePolicy(sizePolicy)
        self.Difficulty = QComboBox(self.centralwidget)
        self.Difficulty.addItem("")
        self.Difficulty.addItem("")
        self.Difficulty.addItem("")
        self.Difficulty.addItem("")
        self.Difficulty.addItem("")
        self.Difficulty.addItem("")
        self.Difficulty.setObjectName(u"Difficulty")
        self.Difficulty.setGeometry(QRect(650, 150, 131, 22))
        self.DifficultyLabel = QLabel(self.centralwidget)
        self.DifficultyLabel.setObjectName(u"DifficultyLabel")
        self.DifficultyLabel.setGeometry(QRect(650, 130, 51, 16))
        self.IWAD_List = QListWidget(self.centralwidget)
        self.IWAD_List.setObjectName(u"IWAD_List")
        self.IWAD_List.setGeometry(QRect(10, 40, 161, 301))
        self.IWADLABEL = QLabel(self.centralwidget)
        self.IWADLABEL.setObjectName(u"IWADLABEL")
        self.IWADLABEL.setGeometry(QRect(10, 20, 37, 12))
        self.Mod_List = QListWidget(self.centralwidget)
        self.Mod_List.setObjectName(u"Mod_List")
        self.Mod_List.setGeometry(QRect(180, 40, 161, 301))
        self.ModLabel = QLabel(self.centralwidget)
        self.ModLabel.setObjectName(u"ModLabel")
        self.ModLabel.setGeometry(QRect(180, 20, 37, 12))
        self.MapPackLabel = QLabel(self.centralwidget)
        self.MapPackLabel.setObjectName(u"MapPackLabel")
        self.MapPackLabel.setGeometry(QRect(350, 20, 71, 16))
        sizePolicy1 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.MapPackLabel.sizePolicy().hasHeightForWidth())
        self.MapPackLabel.setSizePolicy(sizePolicy1)
        self.MapPackList = QListWidget(self.centralwidget)
        self.MapPackList.setObjectName(u"MapPackList")
        self.MapPackList.setGeometry(QRect(350, 40, 161, 301))
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(640, 20, 151, 551))
        self.StartDoom = QPushButton(self.groupBox)
        self.StartDoom.setObjectName(u"StartDoom")
        self.StartDoom.setGeometry(QRect(10, 520, 131, 21))
        self.Settings = QPushButton(self.groupBox)
        self.Settings.setObjectName(u"Settings")
        self.Settings.setGeometry(QRect(10, 460, 131, 21))
        self.Exit = QPushButton(self.groupBox)
        self.Exit.setObjectName(u"Exit")
        self.Exit.setGeometry(QRect(10, 490, 131, 21))
        self.IWAD_DESC = QTextEdit(self.centralwidget)
        self.IWAD_DESC.setObjectName(u"IWAD_DESC")
        self.IWAD_DESC.setGeometry(QRect(10, 370, 161, 121))
        self.MOD_DESC = QTextEdit(self.centralwidget)
        self.MOD_DESC.setObjectName(u"MOD_DESC")
        self.MOD_DESC.setGeometry(QRect(180, 370, 161, 121))
        self.MapPack_Desc = QTextEdit(self.centralwidget)
        self.MapPack_Desc.setObjectName(u"MapPack_Desc")
        self.MapPack_Desc.setGeometry(QRect(350, 370, 161, 121))
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(0, 350, 521, 151))
        self.groupBox_2.setAlignment(Qt.AlignCenter)
        self.IWAD_RATING_SLIDER = QSlider(self.centralwidget)
        self.IWAD_RATING_SLIDER.setObjectName(u"IWAD_RATING_SLIDER")
        self.IWAD_RATING_SLIDER.setGeometry(QRect(10, 530, 160, 16))
        self.IWAD_RATING_SLIDER.setMinimum(1)
        self.IWAD_RATING_SLIDER.setMaximum(5)
        self.IWAD_RATING_SLIDER.setOrientation(Qt.Horizontal)
        self.MOD_RATING_SLIDER = QSlider(self.centralwidget)
        self.MOD_RATING_SLIDER.setObjectName(u"MOD_RATING_SLIDER")
        self.MOD_RATING_SLIDER.setGeometry(QRect(180, 530, 160, 16))
        self.MOD_RATING_SLIDER.setMinimum(1)
        self.MOD_RATING_SLIDER.setMaximum(5)
        self.MOD_RATING_SLIDER.setOrientation(Qt.Horizontal)
        self.MAPPACK_RATING_SLIDER = QSlider(self.centralwidget)
        self.MAPPACK_RATING_SLIDER.setObjectName(u"MAPPACK_RATING_SLIDER")
        self.MAPPACK_RATING_SLIDER.setGeometry(QRect(350, 530, 160, 16))
        self.MAPPACK_RATING_SLIDER.setMinimum(1)
        self.MAPPACK_RATING_SLIDER.setMaximum(5)
        self.MAPPACK_RATING_SLIDER.setOrientation(Qt.Horizontal)
        self.IWAD_RATING = QLabel(self.centralwidget)
        self.IWAD_RATING.setObjectName(u"IWAD_RATING")
        self.IWAD_RATING.setGeometry(QRect(80, 540, 16, 16))
        self.IWAD_RATING.setAlignment(Qt.AlignCenter)
        self.MOD_RATING = QLabel(self.centralwidget)
        self.MOD_RATING.setObjectName(u"MOD_RATING")
        self.MOD_RATING.setGeometry(QRect(250, 540, 16, 16))
        self.MOD_RATING.setAlignment(Qt.AlignCenter)
        self.MAP_RATING = QLabel(self.centralwidget)
        self.MAP_RATING.setObjectName(u"MAP_RATING")
        self.MAP_RATING.setGeometry(QRect(420, 540, 16, 16))
        self.MAP_RATING.setAlignment(Qt.AlignCenter)
        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(0, 500, 521, 61))
        self.groupBox_3.setAlignment(Qt.AlignCenter)
        self.groupBox_4 = QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(0, 0, 521, 351))
        self.groupBox_4.setAlignment(Qt.AlignCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.groupBox_4.raise_()
        self.groupBox_3.raise_()
        self.groupBox_2.raise_()
        self.groupBox.raise_()
        self.MapSelect.raise_()
        self.StartAtSelectedMap.raise_()
        self.FirstMapStart.raise_()
        self.MainMenuStart.raise_()
        self.Difficulty.raise_()
        self.DifficultyLabel.raise_()
        self.IWAD_List.raise_()
        self.IWADLABEL.raise_()
        self.Mod_List.raise_()
        self.ModLabel.raise_()
        self.MapPackLabel.raise_()
        self.MapPackList.raise_()
        self.IWAD_DESC.raise_()
        self.MOD_DESC.raise_()
        self.MapPack_Desc.raise_()
        self.IWAD_RATING_SLIDER.raise_()
        self.MOD_RATING_SLIDER.raise_()
        self.MAPPACK_RATING_SLIDER.raise_()
        self.IWAD_RATING.raise_()
        self.MOD_RATING.raise_()
        self.MAP_RATING.raise_()
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.StartAtSelectedMap.setText(QCoreApplication.translate("MainWindow", u"Load Map:", None))
        self.FirstMapStart.setText(QCoreApplication.translate("MainWindow", u"AutoLoad Map", None))
        self.MainMenuStart.setText(QCoreApplication.translate("MainWindow", u"Start at main menu", None))
        self.Difficulty.setItemText(0, QCoreApplication.translate("MainWindow", u"Default", None))
        self.Difficulty.setItemText(1, QCoreApplication.translate("MainWindow", u"Very Easy", None))
        self.Difficulty.setItemText(2, QCoreApplication.translate("MainWindow", u"Easy", None))
        self.Difficulty.setItemText(3, QCoreApplication.translate("MainWindow", u"Normal", None))
        self.Difficulty.setItemText(4, QCoreApplication.translate("MainWindow", u"Hard", None))
        self.Difficulty.setItemText(5, QCoreApplication.translate("MainWindow", u"Very Hard", None))

        self.DifficultyLabel.setText(QCoreApplication.translate("MainWindow", u"Difficulty", None))
        self.IWADLABEL.setText(QCoreApplication.translate("MainWindow", u"IWAD", None))
        self.ModLabel.setText(QCoreApplication.translate("MainWindow", u"Mod", None))
        self.MapPackLabel.setText(QCoreApplication.translate("MainWindow", u"Map Pack", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Launch Settings", None))
        self.StartDoom.setText(QCoreApplication.translate("MainWindow", u"Start Doom", None))
        self.Settings.setText(QCoreApplication.translate("MainWindow", u"Settings", None))
        self.Exit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Descriptions", None))
        self.IWAD_RATING.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.MOD_RATING.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.MAP_RATING.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Rating", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"Load Selection", None))
    # retranslateUi

